/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalgptRouteImport } from './routes/localgpt'
import { Route as OutlookSignatureManagementRouteImport } from './routes/outlook-signature-management'
import { Route as PreposRouteImport } from './routes/prepos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalgptRoute = LocalgptRouteImport.update({
  id: '/localgpt',
  path: '/localgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookSignatureManagementRoute =
  OutlookSignatureManagementRouteImport.update({
    id: '/outlook-signature-management',
    path: '/outlook-signature-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreposRoute = PreposRouteImport.update({
  id: '/prepos',
  path: '/prepos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/localgpt': typeof LocalgptRoute
  '/outlook-signature-management': typeof OutlookSignatureManagementRoute
  '/prepos': typeof PreposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/localgpt': typeof LocalgptRoute
  '/outlook-signature-management': typeof OutlookSignatureManagementRoute
  '/prepos': typeof PreposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/localgpt': typeof LocalgptRoute
  '/outlook-signature-management': typeof OutlookSignatureManagementRoute
  '/prepos': typeof PreposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/localgpt' | '/outlook-signature-management' | '/prepos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/localgpt' | '/outlook-signature-management' | '/prepos'
  id:
    '__root__' | '/' | '/localgpt' | '/outlook-signature-management' | '/prepos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalgptRoute: typeof LocalgptRoute
  OutlookSignatureManagementRoute: typeof OutlookSignatureManagementRoute
  PreposRoute: typeof PreposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localgpt': {
      id: '/localgpt'
      path: '/localgpt'
      fullPath: '/localgpt'
      preLoaderRoute: typeof LocalgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook-signature-management': {
      id: '/outlook-signature-management'
      path: '/outlook-signature-management'
      fullPath: '/outlook-signature-management'
      preLoaderRoute: typeof OutlookSignatureManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepos': {
      id: '/prepos'
      path: '/prepos'
      fullPath: '/prepos'
      preLoaderRoute: typeof PreposRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalgptRoute: LocalgptRoute,
  OutlookSignatureManagementRoute: OutlookSignatureManagementRoute,
  PreposRoute: PreposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
